name: publish features

on:
  push:
    branches: [main]
    paths: ["features/src/**"]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish features to GHCR
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "features/src"
          oci-registry: ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
